service: image-tagging-filter

plugins:
  - serverless-plugin-log-retention
  - serverless-deployment-bucket

frameworkVersion: '3'

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  deploymentBucket:
    name: apps-${self:provider.region}.deploys
    blockPublicAccess: true
    serverSideEncryption: AES256
    tags:
      Environment: develop

functions:
  tag:
    handler: handler.tag
    role: arn:aws:iam::489716104000:role/image-tagging-filter-role
    events:
      - sns: arn:aws:sns:us-east-1:489716104000:s3-handler-images-topic
    logRetentionInDays: 7
