service: image-tagging-filter

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  tag:
    handler: handler.tag
    role: arn:aws:iam::489716104000:role/image-tagging-filter-role
    events:
      - sns: arn:aws:sns:us-east-1:489716104000:s3-handler-images-topic
