service: image-tagging-filter

plugins:
  - serverless-plugin-log-retention
  - serverless-deployment-bucket

frameworkVersion: '3'

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  deploymentBucket:
    name: apps-${self:provider.region}.deploys
    blockPublicAccess: true
    serverSideEncryption: AES256
    tags:
      Environment: develop

functions:
  tag:
    handler: handler.tag
    role: ${ssm:/image-tagging-filter/lambda-image-tagging-role}
    events:
      - sns: ${ssm:/http-handler/sns-handler-images-topic}
    logRetentionInDays: 7
