service: thumbnail-handler

plugins:
  - serverless-plugin-log-retention
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  thumbnail:
    handler: handler.thumbnail
    role: arn:aws:iam::489716104000:role/thumbnail-handler-role
    events:
      - sns: arn:aws:sns:us-east-1:489716104000:s3-handler-images-topic
    logRetentionInDays: 7
