service: http-handler

plugins:
  - serverless-apigw-binary
  - serverless-plugin-log-retention
custom:
  apigwBinary:
    types:
      - 'image/jpeg'

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  upload:
    handler: handler.upload
    role: arn:aws:iam::489716104000:role/http-handler-role
    events:
     - http:
         path: images
         method: post
    logRetentionInDays: 7
