service: http-handler

plugins:
  - serverless-apigw-binary
  - serverless-plugin-log-retention
  - serverless-deployment-bucket

custom:
  apigwBinary:
    types:
      - 'image/jpeg'

frameworkVersion: '3'

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  deploymentBucket:
    name: apps-${self:provider.region}.deploys
    blockPublicAccess: true
    serverSideEncryption: AES256
    tags:
      Environment: develop

functions:
  upload:
    handler: handler.upload
    role: arn:aws:iam::489716104000:role/http-handler-role
    events:
     - http:
         path: images
         method: post
    logRetentionInDays: 7

  get:
    handler: handler.get
    role: arn:aws:iam::489716104000:role/image-handler-consumer-role
    vpc:
      subnetIds:
        - subnet-06b2176c7e2a427d5
        - subnet-037ee7749f1ac10d4
        - subnet-070af891c6371b94d
      securityGroupIds:
        - sg-0d5fa29a0dd1bbf19
    events:
     - http:
         path: images
         method: get
    logRetentionInDays: 7