service: filter-handler

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  filter:
    handler: handler.filter
    role: arn:aws:iam::489716104000:role/thumbnail-handler-role
    events:
      - sns: arn:aws:sns:us-east-1:489716104000:s3-handler-images-topic
