service: filter-handler

plugins:
  - serverless-plugin-log-retention
  - serverless-deployment-bucket

frameworkVersion: '3'

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  deploymentBucket:
    name: apps-${self:provider.region}.deploys
    blockPublicAccess: true
    serverSideEncryption: AES256
    tags:
      Environment: develop

functions:
  filter:
    handler: handler.filter
    role: ${ssm:/thumbnail-handler/lambda-thumbnail-handler-role}
    events:
      - sns: ${ssm:/http-handler/sns-handler-images-topic}
    logRetentionInDays: 7
